import fs from 'node:fs/promises'

import { command } from '@kidd-cli/core'
import { compact } from 'es-toolkit'

import { createPaths } from '../lib/paths.ts'
import type { Paths } from '../lib/paths.ts'

/**
 * Remove zpress build artifacts and caches.
 *
 * Deletes `.zpress/cache/`, `.zpress/content/`, and `.zpress/dist/`.
 * Safe to run at any time — all directories are regenerated by `sync` and `build`.
 *
 * @param paths - Resolved project paths
 * @returns Names of directories that were actually removed
 */
export async function clean(paths: Paths): Promise<readonly string[]> {
  const results = await Promise.all(
    cleanTargets(paths).map(async ({ dir, label }) => {
      // oxlint-disable-next-line security/detect-non-literal-fs-filename -- safe: removing known zpress output directories
      const exists = await fs.stat(dir).catch(() => null)
      if (exists) {
        // oxlint-disable-next-line security/detect-non-literal-fs-filename -- safe: removing known zpress output directories
        await fs.rm(dir, { recursive: true, force: true })
        return label
      }
      return null
    })
  )

  return compact(results)
}

/**
 * Registers the `clean` CLI command to remove build artifacts and caches.
 */
export default command({
  name: 'clean',
  description: 'Remove build artifacts, synced content, and build cache',
  handler: async (ctx) => {
    const paths = createPaths(process.cwd())
    ctx.log.intro('zpress clean')

    const removed = await clean(paths)

    if (removed.length > 0) {
      ctx.log.success(`Removed: ${removed.join(', ')}`)
    } else {
      ctx.log.info('Nothing to clean')
    }

    ctx.log.outro('Done')
  },
})

// ---------------------------------------------------------------------------
// Private
// ---------------------------------------------------------------------------

/**
 * Build the list of directories to remove for a given set of paths.
 *
 * @private
 * @param paths - Resolved project paths
 * @returns Array of directory/label pairs to clean
 */
function cleanTargets(paths: Paths): readonly { readonly dir: string; readonly label: string }[] {
  return [
    { dir: paths.cacheDir, label: 'cache' },
    { dir: paths.contentDir, label: 'content' },
    { dir: paths.distDir, label: 'dist' },
  ]
}
